### ISSUE TITLE
Multi-Factor Authentication

### ISSUE THREAD

**Issue by dschnabel** [supabase-community/auth-py#234]
Are there considerations to support [Multi-Factor Authentication](https://supabase.com/docs/guides/auth/auth-mfa)?

(I can't seem to find anything related to MFA in `supabase-py`)

**Comment by J0** [comment]
Hey @dschnabel,

Thanks for your patience. Wanted to update you that there's now [MFA support](https://supabase.com/docs/reference/python/auth-mfa-challenge)

If it's still relevant for your use case do give it a try and let us know if there are any issues

**Comment by dschnabel** [comment]
Hi @J0, I don't remember exactly what our use case was but it's good that you have put this in place. If I need this again in the future, I will know that MFA is now supported!
