### ISSUE TITLE
Async memory session store crashing because get/set methods are sync not async

### ISSUE THREAD

**Issue by christopherdbull** [supabase-community/auth-py#399]
https://github.com/supabase-community/auth-py/blob/568101128a27280600da86780590fce62025410e/gotrue/_async/storage.py#L29

Hey, I've been trying to use the supabase python client - ironically to speed up my development but have instead spent the last few days bughunting hah. I was trying to get the session and I kept getting NoneType await/async errors. Removed the async declaration of this method (as it never actually awaits anything) and it works. 

I'm not a python dev so unsure if I'm best placed to fix this, but the bug is real and should be an easy one for someone who knows the stack - picked python for this project as all the fun ml libs are on this side of the fence. 

Cheers

Edit: found another bit while digging. The async auth client had this at `_storage` `<gotrue._sync.storage.SyncMemoryStorage object at 0x109001110>`

**Comment by silentworks** [comment]
Are you using this library directly or using it through the `supabase` python package? If through the `supabase` package please upgrade to the latest version (`2.3.3`) and this should be fixed.

**Comment by silentworks** [comment]
Closing this out as it's had no reply from OP for over a month.
