### ISSUE TITLE
Add message_id field to sign_in_with_otp

### ISSUE THREAD

**Issue by J0** [supabase-community/auth-py#406]
# Chore

We need to add the newly introduced `message_id` field to the Python Pydantic model so that developers can properly send OTP messages without error 

Spinoff of [this issue](https://github.com/supabase-community/auth-py/issues/321#issuecomment-1894675526)

API  specification of `message_id`: https://github.com/supabase/gotrue/blob/master/openapi.yaml#L474

Return Type for JS lib: https://github.com/supabase/gotrue-js/blob/master/src/lib/types.ts#L131

**Comment by PrayusShrestha** [comment]
Is there a short-term workaround for this?
