### ISSUE TITLE
ResourceWarning: unclosed transport <_SelectorSocketTransport fd=60>

### ISSUE THREAD

**Issue by ToniRV** [supabase-community/auth-py#432]
# Bug report

## Describe the bug

Tons of ResourceWarning messages when running this package.
Somehow they all disappear if I delete this line in set_session
Not sure why?

```
        self._notify_all_subscribers("TOKEN_REFRESHED", session)
```

**Comment by silentworks** [comment]
In what environment is this? can you provide a reproducible example repo showcasing the issue as I haven't seen this being reported by anyone else nor have I had this issue in my own projects.

**Comment by silentworks** [comment]
Closing this out as the OP hasn't replied.
