### ISSUE TITLE
Pypi wheel build

### ISSUE THREAD

**Issue by sapphire008** [supabase-community/auth-py#433]
# Chore

## Describe the chore

This may quality as a chore. I have noticed that the Pypi still has version 2.1.0 which is from last December, while the repo has version 2.4.1 now. I wonder if this is related to the renaming that is mentioned in the Readme: https://pypi.org/project/gotrue/

Looking forward to the new releases.

## Additional context

Pypi version:
![Screenshot 2024-02-23 at 12 07 11 AM](https://github.com/supabase-community/auth-py/assets/3713023/7a0f6d0f-2e95-4318-93b0-eb358e971bc4)

Repo version:
![Screenshot 2024-02-23 at 12 07 27 AM](https://github.com/supabase-community/auth-py/assets/3713023/40325086-7368-4b9d-8677-8e79ea962b1f)

**Comment by silentworks** [comment]
This is an issue indeed. I will look into getting this resolved soon and you are correct about the package renaming being the cause. I can see the build failed to do a release to PyPi due to the package name.

**Comment by mansueli** [comment]
Thanks for reporting. I've manually pushed the new version (2.4.1). 
But we need to fix the CI/CD.

https://pypi.org/project/gotrue/
